### ISSUE TITLE
The VR player's view mirror on the PC can't be switched to the main viewport

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab#87] opened 2019-08-14 11:13 UTC

**Comment by kb173** [comment] 2019-08-21 12:48
For performance reasons, we will simply render the VR view onto the desktop. If I recall correctly, this happens automatically when no other camera renders onto the PC viewport.

**Comment by kb173** [comment] 2019-08-25 08:37
This article explains the relationships between PC and VR viewports: https://godotengine.org/article/godot-3-vr-and-ar-support

If I understand correctly, we simply have to do `viewport.arvr = true` with the viewport that is mirroring the VR perspective. ("if the main viewport is used, the main viewport will show a raw version of the left eyes render while the stereoscopic result is sent to the headset") We can do this in the FirstPersonPC script in `_set_vr_mode`.

I will add and test this with our VR headset on Tuesday.

**Comment by kb173** [comment] 2019-08-27 11:03
Setting arvr to true works, but performance is bad. Might need to do it in PerspectiveHandler

**Comment by kb173** [comment] 2019-08-28 15:31
Doing it in the PerspectiveHandler works, and the solution is quite performant. However, switching around viewports gets very odd results (e.g. VR view, but with minimap tiles). We probably need to handle the ARVR viewport stuff and render layers better

**Comment by kb173** [comment] 2019-09-02 15:09
63cacba might fix the behavior, but we need to test it on the workshop PC while moving the VR headset to be sure.

**Comment by kb173** [comment] 2019-09-03 14:45
The referenced commits haven't entirely fixed it: When switching, the viewports are strangely stretched, the performance tanks and sometimes, when closing the VR view, the game just crashes (since 724e2dd). This is most likely related to the new `ARVRInterface::uninitialize()` call.

Interestingly, this only happens if a ARVR interface is actually present and a real VR device was activated. Testing on my laptop, everything works perfectly. So it's probably related to that ARVRInterface...

**Comment by kb173** [comment] 2019-09-04 09:11
ARVR being initialized / uninitialized seems to cause some unpredictable behavior... this ranges from performance getting worse when doing it repeatedly and weird viewport stretching to straight up `drivers/unix/net_socket_posix.cpp:190 - Socket error: 10054` crashes.

These issues have been reported to the godot_openvr repository (issue 66).

So it seems like switching the VR mirror view between viewports is currently not feasible... @chrisgraf should we just instance the VR mirror view into the main viewport, and leave the mini viewport for switching between other views? Or the other way around? Or maybe even add a 3rd viewport for mirroring when VR is active?

**Comment by kb173** [comment] 2019-09-04 09:15
Not committing the changes I made when debugging this - they made some things with switching the VR view better, but it seems like it arrived at a dead end and can't solve the issue completely,

**Comment by chrisgraf** [comment] 2019-09-04 11:27
a 3rd viewport which is just visible in vr mode seems a solid solution for me

**Comment by chrisgraf** [comment] 2019-09-04 11:28
what will the first person view show when vr mode is enabled?

**Comment by kb173** [comment] 2019-09-04 11:32
I was leaning towards that as well :+1: What do you think, bottom left or top right (above the minimap)?

Since the VR player practically replaces the PC first person view when it's active, maybe we should just hide the first person button when VR is active?

**Comment by chrisgraf** [comment] 2019-09-04 11:34
Can we replace the minimap view with that (I dont think that we need 3 viewports - at least for the workshops)? The first person view icon will not be shown. If it currently is the main view we will automatically replace the main view with the 3rd person view (or is the map view better?)

**Comment by kb173** [comment] 2019-09-04 11:37
Yes, we can do that! I'd put the 3rd person view into the main viewport, since that's the most practical for observing / controlling the VR player.

**Comment by kb173** [comment] 2019-09-04 16:34
Done with 1fe1dbd02de2ba3074c7466d09a91d8acbe4283f. This setup seems to work well and feels pretty intuitive too. Moving this to 'possible future' for when we get info / bugfixes for what's going on with VR viewports in Godot, since it would be nice to eventually integrate it into our Perspective system as originally planned.

**Comment by kb173** [comment] 2020-12-21 11:31
Todo: build a reproduction project and report to Godot VR if it seems like a bigger (Godot) issue.

If no problem for performance: Just remove the viewports. We need to check whether some VR rendering is still done in the background then.

**Comment by MathiasBaumgartinger** [comment] 2022-10-19 11:39
This is no longer relevant due to the following reasons:
- The UI system no longer allows for switching multiple viewports
- The VR screen is no longer showed on the display but, only the VR glass' view direction is indicated
- The VR screen in general was a bit painful to work with as it was somewhat limitated

**Closed by MathiasBaumgartinger** 2022-10-19 11:39 UTC
Labels: limitation
