### ISSUE TITLE
File Chooser if geodata is missing

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab#277] opened 2022-04-28 12:25 UTC
currently if you miss to configure the gpkg path correctly it will load for eternity. A file chooser to select the gpkg to load would be convenient.

**Comment by MathiasBaumgartinger** [comment] 2022-05-02 12:00
@chrisgraf this should be fixed with [4a84e92](https://github.com/boku-ilen/landscapelab/commit/4a84e9227c593ebec5eb43973a6a78131f30de67)

I did not create a pull request as this was not such an impactful change and the functionality seems to work properly. Anyways, could you confirm the behaviour is as expected? 😄

**Comment by chrisgraf** [comment] 2022-05-02 12:04
ERROR: Condition "err" is true. Returned: err
   at: load_source_code (modules/gdscript/gdscript.cpp:787)
ERROR: Cannot load source code from file 'res://UI/MenuBar/MenuBar.gd'.
   at: load (modules/gdscript/gdscript.cpp:2184)
ERROR: Failed loading resource: res://UI/MenuBar/MenuBar.gd. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:270)
WARNING: Couldn't load external resource: res://UI/MenuBar/MenuBar.gd
     at: _parse_ext_resource (scene/resources/resource_format_text.cpp:157)
ERROR: Index p_idx = 1 is out of bounds (edited_scene.size() = 1).
   at: remove_scene (editor/editor_data.cpp:531)

**Comment by MathiasBaumgartinger** [comment] 2022-05-02 12:07
Sorry seems i forgot to push new script/scene

**Comment by chrisgraf** [comment] 2022-05-02 12:07
some dependency seems to be missing .. it fails at the end with MenuUI.gd:33 function missing in HBoxContainer

**Comment by chrisgraf** [comment] 2022-05-02 15:47
Now I am getting the following error with the LL_weiden.gpkg after selecting it via the UI:

![image](https://user-images.githubusercontent.com/1245084/166264299-e5dd3664-444f-484e-a7bf-a5440218d558.png)

**Comment by MathiasBaumgartinger** [comment] 2022-05-02 15:48
Weird ... The exact same ``.gpkg`` works when it is loaded from configuration.ini?

**Comment by chrisgraf** [comment] 2022-05-02 15:54
ah no .. same error. It only appears when I launch via the Godot Editor... but the data is not completely loaded if I start it directly - so the error is in the gpkg?

**Comment by MathiasBaumgartinger** [comment] 2022-05-02 15:55
> ah no .. same error. It only appears when I launch via the Godot Editor... but the data is not completely loaded if I start it directly - so the error is in the gpkg?

Probably caused by an outdated gpkg ... 
Could you try and run https://github.com/boku-ilen/landscapelab-geodaten/blob/master/gpkg/update-vegetation.sh on it?

**Comment by MathiasBaumgartinger** [comment] 2022-06-08 11:22
Havent got any answers and it seems to work fine for me and @kb173 - closing.

**Closed by MathiasBaumgartinger** 2022-06-08 11:22 UTC
Labels: enhancement
