### ISSUE TITLE
dynamic energy values in tooltips

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab#111] opened 2019-08-27 11:23 UTC
URL for requesting energy production of a single asset ^energy_contribution/(?P<asset_id>(\d+))/asset.json$

**Comment by MathiasBaumgartinger** [comment] 2019-08-27 15:19
This should work as intended, server values are still missing however.

**Comment by chrisgraf** [comment] 2019-09-03 11:48
the URL will change .. will be posted here

**Comment by MathiasBaumgartinger** [comment] 2019-09-07 13:01
@chrisgraf Please tag me once the URL is updated.

**Comment by chrisgraf** [comment] 2019-09-07 15:33
@MathiasBaumgartinger : take a look at the current push .. I think the URLs should not change anymore

**Comment by kb173** [comment] 2019-09-11 23:06
The request needed for the tooltip is currently not working due to #136

**Comment by kb173** [comment] 2019-09-18 13:28
The last problem with this was fixed in 91a2caa

**Closed by kb173** 2019-09-18 13:28 UTC
Labels: enhancement
