### ISSUE TITLE
location indicator in minimap does not track the player location after rotation

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab#43] opened 2019-05-21 11:51 UTC
After rotation the location indicator in minimap is off center (we currently just have follow mode implemented so it should be in center all the time) .. after switching between miniview and full view the location indicator is placed on the correct location again

**Comment by kb173** [comment] 2019-05-21 17:07
It seems like this is a known limitation of the MinimapIcon:
```it's parent object should not be able to rotate around the x- or z-axis``` 

I believe the rotation and position logic could be made simpler by turning it into a Sprite instead of a Mesh. Or is there a use case I'm not thinking of which makes this implementation more feasible?

**Comment by MathiasBaumgartinger** [comment] 2019-05-30 19:09
Works to a certain extent. Commit 96a685c reworked the handling to billboards. The player icon still does not work as intended, but the position is correct: With Godot v3.2  billboard rotation will be included so the player icon will only rotate around z-axis. See Godot issue nr. 18296 for further information. Po

**Comment by chrisgraf** [comment] 2019-06-06 17:43
works sufficiantly enough for 0.3

**Comment by chrisgraf** [comment] 2019-08-05 22:00
as 3.2 will not be available for the workshops, we will need to implement our own shader

**Comment by kb173** [comment] 2019-08-12 19:55
The custom shader was written (in part generated from the existing material) and implemented in the MinimapIcon in ffa3871. Rotation now works properly.

**Closed by kb173** 2019-08-12 19:55 UTC
Labels: bug, godot-issue
