### ISSUE TITLE
strange error messages at startup about a missing node

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab#40] opened 2019-05-18 03:08 UTC
ERROR: get_global_transform: Condition ' !is_inside_tree() ' is true. returned:
Transform()
   At: scene/3d/spatial.cpp:266
ERROR: Node not found: ViewportContainer/Viewport
   At: scene/main/node.cpp:1382
ERROR: ViewportTexture: Path to node is invalid
   At: scene/main/viewport.cpp:69
ERROR: get_global_transform: Condition ' !is_inside_tree() ' is true. returned:
Transform()
   At: scene/3d/spatial.cpp:266
ERROR: Node not found: ViewportContainer/Viewport
   At: scene/main/node.cpp:1382
ERROR: ViewportTexture: Path to node is invalid
   At: scene/main/viewport.cpp:69

this is repeated quite a lot .. the error probably comes from the ToolTip3D.tcsn .. there is the following reference which is not displayed in the Node view of Godot itself:

[sub_resource type="ViewportTexture" id=2]
viewport_path = NodePath("ViewportContainer/Viewport")

Could you take a look how to address this?

**Comment by kb173** [comment] 2019-05-18 17:51
Removing the 'local_to_scene' flag from the Sprite3D texture in Tooltip3D removes this error, however, it also makes tooltips not functional, while they work perfectly fine when the error is displayed...

It seems like it could be a Godot editor issue, since there is not actually a problem with the viewport path. Similar issues have been reported, but those are marked as fixed. We might want to open a new one for this particular case.

**Comment by chrisgraf** [comment] 2019-06-24 09:51
Moving this to 0.4 as it does not seem to affect the display of the tooltip3D elements

**Comment by kb173** [comment] 2019-08-02 22:40
This is identical to Godot issue 27790. The workaround suggested there works for us and was implemented in 0eae98d.

The message `ERROR: get_global_transform: Condition ' !is_inside_tree() ' is true. returned:
Transform()` remains. It is caused by the Windmill's `set_wind_direction()`. Presumably, it is called before the node is actually added to the tree, and thus `look_at()` can't obtain the global position.

We could check for this and catch up as soon as the node is actually inside the tree.

**Comment by kb173** [comment] 2019-08-02 22:44
The remaining error message was fixed in a7fd233 as suggested in the earlier comment.

**Closed by kb173** 2019-08-02 22:44 UTC
Labels: bug, godot-issue
