### ISSUE TITLE
mouse inputs should be related to the viewpoint the mouse is currently over

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab#48] opened 2019-05-21 16:01 UTC

**Comment by MathiasBaumgartinger** [comment] 2019-05-30 19:05
WIth b92418c and f36f50f this should be closed. Can someone verify if it is working as intended?

**Comment by chrisgraf** [comment] 2019-06-01 21:03
for me this is not working

**Comment by chrisgraf** [comment] 2019-06-20 21:02
we can not prevent the forwarding of the user controls currently

**Comment by chrisgraf** [comment] 2019-07-04 00:11
as this may be solved with a later version of godot we postpone this issue to 0.4 for now

**Comment by chrisgraf** [comment] 2019-07-11 00:31
this is partially solved now by checking the viewport the mouse is over currently but still overlapped viewports receive the signal

**Comment by kb173** [comment] 2019-08-25 21:03
I found [`_unhandled_input`](https://docs.godotengine.org/en/3.1/classes/class_node.html#class-node-method-unhandled-input) which seems to be related: `_input` reacts to any input, whereas `_unhandled_input` only reacts to input which hasn't been handled by GUI or (explicitly) by our code.

Not quite working right away though - simply switching out the functions causes no gameplay input to work...

**Comment by kb173** [comment] 2019-08-25 21:37
With this in the ViewportContainer of the PerspectiveHandler:

```
func _unhandled_input(event):
	print(event)
```

The main viewport's input works with `_unhandled_input`. Only with that script though, and the mouse filter set to 'Ignore'. Very strange... 

It's promising though - UI inputs such as scrolling in the UI don't have an effect on the player anymore!

**Comment by kb173** [comment] 2019-08-25 22:01
With 110d333, input seems to be working as intended for me! Only the viewport which the mouse is over handles the input, and GUI input isn't handled by the player nodes.

The required workaround mentioned above is still very strange, we should investigate further if we're doing something wrong somewhere else.

@luxkon Can you do some testing for this? Try various clicks, buttons, dragging, etc. and verify whether it's always handled (only) in the expected way.

**Comment by luxkon** [comment] 2019-08-26 10:11
If mouse click is pressed while leaving the small screen current Navigation type (1st or 3rd Person) stays activated. Pointing back into the small screen means to navigate in the same mode without Pressing. This stays until the same mouseclick is clicked again. Its the same the other way around. If i keep the mouse clicked in the big screen and Point on the small one.

**Comment by kb173** [comment] 2019-08-26 15:05
Thanks! I believe https://github.com/boku-ilen/landscapelab/commit/b3b33bb81883cff680bdbfc549660b35afaa5723 fixes it. 

Leaving it open for testing until tomorrow, in case we find another bug.

**Comment by kb173** [comment] 2019-09-01 19:08
One more inconvenience we found has been fixed in 4958588. Since we didn't find anything else, I'm closing the issue - if we do find some instance with incorrect or unintuitive mouse handling, we can create a specific new issue for that.

**Closed by kb173** 2019-09-01 19:08 UTC
Labels: godot-issue, needs testing
