### ISSUE TITLE
Extend imaging tool for creating training images

### ISSUE THREAD

**Issue by kb173** [boku-ilen/landscapelab#170] opened 2020-02-10 14:17 UTC
The existing dolly imaging tool can be re-used.

Functionality that needs to be added: Instead of just taking a screenshot, we need to take 2 screenshots: one normal, and one with the training asset completely pink.

Suggestion: Emit a signal after first screenshot with AssetType (or Asset?) as parameter, react to signal in Asset and set material_override, send signal to remove material_override again

**Comment by MathiasBaumgartinger** [comment] 2020-02-11 10:08
With commit 2414386 the imaging camera focus gets visualized.

**Comment by MathiasBaumgartinger** [comment] 2020-02-13 15:45
Commit 7572553fd741559bd6a03e040720d8ad6eb7928d from @kb173 added the different colours. With teh interpolation script from 52553d7d604286a4d038e91315a30ab2d00417b9 its now fully functioning as intended. 👍 closing

**Closed by MathiasBaumgartinger** 2020-02-13 15:45 UTC
Labels: enhancement
