### ISSUE TITLE
Teleportation: First-Person registers every click although it is in the miniview.

### ISSUE THREAD

**Issue by MathiasBaumgartinger** [boku-ilen/landscapelab#138] opened 2019-09-18 13:41 UTC
This problem could easily be fixed by removing the feature in the First-Person. Is it really required as a functionality for First-Person as well? Then we would have to find a workaround.

**Comment by MathiasBaumgartinger** [comment] 2019-09-19 09:28
As discussed with Tom this will be tagged with possible future.

**Comment by kb173** [comment] 2020-02-21 10:51
Duplicate of #116

**Closed by kb173** 2020-02-21 10:51 UTC
Labels: bug
