### ISSUE TITLE
Re-add VR teleport functionality

### ISSUE THREAD

**Issue by kb173** [boku-ilen/landscapelab#164] opened 2019-10-17 12:58 UTC
The left controller should handle base functionality such as teleportation.

This functionality is already implemented, just not fully compatible with recent changes in the terrain collider and global player position.

**Comment by MathiasBaumgartinger** [comment] 2020-03-03 16:02
Duplicate of another issue #201. As i have documented my progress there i will close this issue however.

**Closed by MathiasBaumgartinger** 2020-03-03 16:02 UTC
Labels: VR, enhancement, needs testing
