### ISSUE TITLE
vegetation creates holes in the ground

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab#49] opened 2019-05-21 16:04 UTC
![image](https://user-images.githubusercontent.com/1245084/58111963-c6419680-7bf2-11e9-9860-b9c00bce7910.png)

**Comment by kb173** [comment] 2019-05-21 17:29
It seems like this is an issue with the heightmap shader - the problem is only visual, it's possible to walk over these holes normally. Perhaps it is related to the images being very small at that zoom.

**Comment by kb173** [comment] 2019-05-22 22:50
Fixed by 935be73 - the problem was that VegetationModules were changing the flags of the heightmap image, which also affected the heightmap used in the shader, since both just held a reference to the same ImageTexture in the cache.

**Closed by kb173** 2019-05-22 22:50 UTC
Labels: bug
